### ISSUE TITLE
fail to compile on Codio

### ISSUE THREAD

**Issue by ghost** [mirage/mirage-www#197]
followed yur instructions here :)
http://anil.recoil.org/2014/03/26/codio-now-has-opam-support.html

Codio Box IDE if you want to check is here.
https://codio.com/gedw99/mirage

When i got to the 2nd last step is failed 
opam install mirage-www -y

Terminal error message.
=-=-= Installing tcpip.1.1.2 =-=-=  
default    Downloading https://opam.ocaml.org/archives/tcpip.1.1.2+opam.tar.gz  
Downloading https://opam.ocaml.org/archives/tcpip.1.1.2+opam.tar.gz  
Building tcpip.1.1.2:  
  make  
  make install  
[ERROR] The compilation of tcpip.1.1.2 failed.  
Removing tcpip.1.1.2.  
  ocamlfind remove tcpip                                                                                                                                                

[ERROR] Due to some errors while processing tcpip.1.1.2, the following actions will NOT proceed:                                                                        
- install mirage-http.1.1.0  
- install mirage-www.1.1.0

**Comment by yomimono** [comment]
I don't think this is relevant any longer.  Please feel free to reopen and comment if you disagree.
