### ISSUE TITLE
is-mirage-broken predicts the future?

### ISSUE THREAD

**Issue by jameshfisher** [mirage/mirage-www#239]
Your [updates page](http://openmirage.org/updates/) has the top result:

> Mirage build status (29 Nov 2014)

That date is in the future -- can that be right?

It looks like that date originates from [this file](https://github.com/mirage/mirage-www/blob/956c42af6c6a21bd47ced2212e18d96dcc8aa089/src/bactrian.ml) which reads

    (*NOTE this file was generated by is-mirage-broken -- DO NOT EDIT*)
    ...
    let entry_for_is_mirage_broken_wikipage =
      {
        updated = date (2014, 11, 29, 19, 00);
        ...

**Comment by hannesm** [comment]
thanks for the report.  is-mirage-broken was outdated, and subsequently removed.
