### ISSUE TITLE
Hello World documentation has been broken by a change to mirage-skeleton.

### ISSUE THREAD

**Issue by ricpruss** [mirage/mirage-www#253]
Not sure if this is the write place to note the issue, I asked on IRC but folks were idled or frantically Christmas shopping.  No big deal but the [hello world page](http://www.openmirage.org/wiki/hello-world), step 4 is broken due to a change in the mirage-skeleton.

Step 4 of the hello world has the following instruction
```
$ curl http://localhost
hello mirage world!
```
This change [Fix the stackv4 example to not use HTTP (which is now Conduit based) ](https://github.com/mirage/mirage-skeleton/commit/41cc1a49666290a11c2350e64a151adda21b3b56) has made Step 4 of the Hello World examples not work as there is no http in stack4 anymore.

**Comment by dongcarl** [comment]
I think #271 fixed it

**Comment by samoht** [comment]
Thanks for noticing.
