### ISSUE TITLE
Update instructions for building mirage-www

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#267]
The DHCP default was changed in https://github.com/mirage/mirage-www/commit/68c8471d140206d8dc0fa3a47a8b0f444e652d3f but the [instructions on the website](http://openmirage.org/wiki/mirage-www) don't reflect this change.  Anyone following the instructions to debug might be confused - cf #265

**Comment by amirmc** [comment]
Actually the site does say

"DHCP is either blank or set to any value (which is considered true). Disabling DHCP assumes a development IP address of 10.0.0.2…"

but I completely skipped past this as I was looking at the incantations themselves. I don't think it's very clear so I'll think of how to improve it.

**Comment by yomimono** [comment]
@amirmc, do you have time to revisit this?  The page in question could still use some attention, and I know you were trying a run-through of the instructions.

**Comment by amirmc** [comment]
Closing this as I think we should look over the instructions afresh (see #539).
