### ISSUE TITLE
Set up a redirect to point people at weekly notes 

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#269]
Redirect http://openmirage.org/wiki/weekly/ to http://openmirage.org/docs/#Weeklycallsandreleasenotes

Alternatively, just make a page at the former URL.

**Comment by marklrh** [comment]
It' easy to do a patter matching as ``[x] when x = "weekly"`` at [line 63 of wiki.ml](https://github.com/mirage/mirage-www/blob/master/src/wiki.ml#L63) and redirect to the ``main_page``, but I failed to figure out how to jump to the section "#Weeklycallsandreleasenotes". Can I have some hints (つд⊂) ?
