### ISSUE TITLE
Docs :: Hello Mirage World seems to be out-of-date

### ISSUE THREAD

**Issue by garasubo** [mirage/mirage-www#279]
Step 4: Networking of Docs:: Hello Mirage World seems to be out-of-date.
In this document, if stackv4 example run, we can `curl localhost` and return `hello mirage world`.
But I tried this, there are no response.
I searched the string "hello" in the source code, but there are no such string in the stackv4 example.

**Comment by talex5** [comment]
There's @heidi-ann's PR to update it here: https://github.com/mirage/mirage-www/pull/271
It should probably be updated for the latest version, which removes the confusing http bits.

**Comment by garasubo** [comment]
I'm ｓorry for my  carelessness.
I miss that PR.

**Comment by talex5** [comment]
No problem - thanks for the reminder! I've merged the update to mirage-www. It should show up in the next deployment.
