### ISSUE TITLE
Travis scripts are broken

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#281]
See https://github.com/mirage/mirage-www/pull/280#issuecomment-73714863

**Comment by amirmc** [comment]
Builds fails because `https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh` returns a `Not Found`

It look like @mor1 is working on a fork of that repo so this will likely remain broken until things are merged upstream into the repo that @samoht has been working on. Maybe I'm going overboard with calls of brittleness but it does make debugging a travis failure more annoying :-P

**Comment by samoht** [comment]
This is because of https://github.com/ocaml/ocaml-travisci-skeleton/pull/24 I've just merged the PR, I'll re-run the Travis tests.

**Comment by mor1** [comment]
...at present the output unikernel from travis won't boot anyway so it's all moot until that's fixed...
