### ISSUE TITLE
Please increase the TTL of http://www.openmirage.org

### ISSUE THREAD

**Issue by mackwic** [mirage/mirage-www#285]
Hi, I really don't know where this issue should be posted, don't hesitate to correct me and I will move the issue where it should be.

So, I am currently in a place where the only Internet is available through 3G and satellite connections, with often 20/25 seconds latency.
http://www.openmirage.org throw a 504 gate timeout around 10seconds, which means that I can't consult the doc when the sky is RF cloudy.

Could you increase the TTL around 30seconds ? It would be very nice of you.

**Comment by avsm** [comment]
I'm not sure which TTL you are referring to here -- do you mean IP TTL?  The 504 gateway timeout is being generated by a proxy on your 3G connection, not our website.  Reporting this issue on https://github.com/mirage/mirage-tcpip/issues is the best place, as it's probably something that can be modified in our TCP/IP stack once we know the problem.
