### ISSUE TITLE
Auto-tweet each item as it gets added to the RSS feed

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#290]
We have a twitter account and we should be auto-tweeting content that gets added to the site. Most of this already ends up in the RSS feed so I wonder that hooking something into that would be a simple way of achieving this (tweet a title and link).

A twitter, unikernel bot could be set up to do this but it would require an awesome name (apparently [roadrunners](https://en.wikipedia.org/wiki/Greater_roadrunner) live in the desert, but then we'd also have to have another unikernel called coyote chasing it).

Write up as Pioneer Project?

**Comment by samoht** [comment]
I'm closing this as I don't think we want this anymore.
