### ISSUE TITLE
Precise instructions on how to run mirage-www socket mode

### ISSUE THREAD

**Issue by lambdaxdotx** [mirage/mirage-www#299]
I have followed your instructions on how to build and run mirage-www on socket mode:
```
$ cd src
$ env NET=socket FS=crunch mirage configure --unix
$ make depend
$ make
$ make run
```
but this fails to run properly, as I got:
```
[...]
read: /wiki/htcaml.md
Fatal error: exception Unix.Unix_error(1, "bind", "")
Called from file "unix/tcpip_stack_socket.ml", line 101, characters 4-41
Called from file "src/core/lwt.ml", line 652, characters 66-69
Re-raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 109, characters 2-28
Makefile:35: recipe for target 'run' failed
make: *** [run] Error 2
```
Using `sudo ./mir-www` all works fine.

**Comment by talex5** [comment]
Try:

    env NET=socket PORT=8080 mirage configure --unix

Unix doesn't allow non-root processes to listen on ports < 1024.

**Comment by lambdaxdotx** [comment]
Yep, that's perfect.
I don't know if it worth changing the mirage-www guide on the website.

**Comment by amirmc** [comment]
Thanks for reporting this!  I've opened #300 as I think we need an automated way of ensuring these work.
