### ISSUE TITLE
Automatically test the getting started instructions

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#300]
We should be able to run tests on the instructions for building mir-www (and any others).  I'm thinking of something similar to the [99 problems page](http://ocaml.org/learn/tutorials/99problems.html) on OCaml.org ([source](https://raw.githubusercontent.com/ocaml/ocaml.org/master/site/learn/tutorials/99problems.md)), but in reverse.  i.e. the code snippets on the page are pulled in from version-controlled source files elsewhere (via some templating magic).

xref: https://github.com/mirage/mirage-www/issues/299, https://github.com/mirage/mirage-www/issues/267, https://github.com/mirage/mirage-www/issues/238

**Comment by yomimono** [comment]
There are folks currently working on this for the new edition of Real World OCaml. I hope we can repurpose their work here (and elsewhere in the Mirage ecosystem).

**Comment by samoht** [comment]
I've added the necessary machinery to do this in #817 using `mdx`. The rest of the work is now tracked by #770 so closing.
