### ISSUE TITLE
New links for links page

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#309]
I'll keep a list here until I (or someone else) gets around to adding them.
- http://www.thoughtworks.com/p2magazine/issue11/the-future-of-cloud/

**Comment by amirmc** [comment]
http://forums.juniper.net/t5/Industry-Solutions-and-Trends/Unikernel-for-Virtual-Network-Functions-VNF/ba-p/277319

**Comment by yomimono** [comment]
Guessing there was intended to be a links page at some point, but the age of this issue suggests that we might be bad at keeping it up to date and removing dead links.  What do you think, @amirmc ?

**Comment by amirmc** [comment]
@yomimono there's a page at https://mirage.io/links which isn't easily reached from the main site (if at all).  We've not been very good at keeping this up to date as it's labour intensive for what it is.

An automated way of adding would stand a better chance. That might be a nice Pioneer Project.

**Comment by amirmc** [comment]
Not sure if I ever added these but closing this anyway.
