### ISSUE TITLE
Error: Out of memory (on blog page)

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#321]
Visit http://openmirage.org/blog/ and you'll see the following error:
`Error: Out of memory`

It's working fine on https://mirage.io/blog

**Comment by amirmc** [comment]
Seems to be working today.

**Comment by amirmc** [comment]
I think this was uncovered and fixed elsewhere (something to do with `Crunch`, I believe).  Closing this.

**Comment by samoht** [comment]
indeed it has been fixed. It was an issue with redirections (typo in the hostname).
