### ISSUE TITLE
How to keep various backends/stacks in sync

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#330]
How do we currently keep the different backends in sync when new content is added?  I assume the unikernel at https://mirage.io is manually built/deployed and at the moment, hence the content is out of sync with http://openmirage.org at the moment  (I typically prefer to point ppl at the mirage.io site where possible).

**Comment by samoht** [comment]
See #317 It is now just a matter of filling the right network configuration parameters in `.travis.yml`. @mor1 you said you might be able to help with that? Or @avsm?

**Comment by mor1** [comment]
Happy to help -- it seems that we need to

1. update `.travis.yml` to build two Xen targets with different `NAME` and
`IP` etc params
2. update `mirage/mirage-www-deployment` so that when `deploy.sh` is run by
the post-merge hook, it determines which (possibly both) of the images have
updated, and invokes `xl` appropriately to destroy and boot said images

That right?

@avsm Are there any particular runes used for booting http://mirage.io, or
is it just a standard `xl create`?


On 19 June 2015 at 16:07, Thomas Gazagnaire <notifications@github.com>
wrote:

> See #317 <https://github.com/mirage/mirage-www/pull/317> It is now just a
> matter of filling the right network configuration parameters in
> .travis.yml. @mor1 <https://github.com/mor1> you said you might be able
> to help with that? Or @avsm <https://github.com/avsm>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/issues/330#issuecomment-113542122>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by samoht** [comment]
> 2. update `mirage/mirage-www-deployment` so that when `deploy.sh` is run by
the post-merge hook, it determines which (possibly both) of the images have
updated, and invokes `xl` appropriately to destroy and boot said images

where is that post-merge hook defined? I don't understand how the final step of the deployment takes place.

**Comment by amirmc** [comment]
> where is that post-merge hook defined? I don't understand how the final step of the deployment takes place.

Do the following notes help? http://amirchaudhry.com/heroku-for-unikernels-pt1/#deployment-scripts (it's possible they're a little out of date -- I haven't checked)

**Comment by samoht** [comment]
@amirmc thanks! actually I found it yesterday: https://github.com/mirage/mirage-www-deployment/pull/2

**Comment by mor1** [comment]
In an idle moment, searching for issues referencing me in and found this one :) 
Is it resolved? The deployment workflow is actually working correctly at the moment I think...

**Comment by yomimono** [comment]
The deployment workflow is working correctly for https://mirage.io , but we need to do some additional work to get http://solo5.mirage.io/ (and any other mirrors we may decide to make) updating automatically as well.

**Comment by samoht** [comment]
Closing as the deployment is now tested and handled by [mirage-ci](https://ci.mirage.io/) - code is [here](https://github.com/ocurrent/ocurrent-deployer/blob/master/src/mirage.ml) and [here](https://github.com/ocurrent/mirage-ci)
