### ISSUE TITLE
Misleading flag in Makefile (IPADDR ?= dhcp)

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-www#338]
The Makefile suggests that you should configure this variable:
```
IPADDR ?= static
```
but actually the `config.ml` does something different:
```
     let staticip =
        let address = Sys.getenv "ADDR" |> Ipaddr.V4.of_string_exn in
        let netmask = Sys.getenv "MASK" |> Ipaddr.V4.of_string_exn in
        let gateways =
          Sys.getenv "GWS" |> split ':' |> List.map Ipaddr.V4.of_string_exn
        in
        { address; netmask; gateways }
      in
      direct_stackv4_with_static_ipv4 console tap0 staticip

    | false ->
      let net =
        try match Sys.getenv "NET" with
          | "socket" -> `Socket
          | _        -> `Direct
        with Not_found -> `Direct
      in
      let dhcp =
        try match Sys.getenv "DHCP" with
          | "1" | "true" | "yes" -> true
          | _  -> false
        with Not_found -> false
      in
```
(I think `NET` is ok but the others are wrong or missing)

**Comment by yomimono** [comment]
I went to patch this as a side effect of building mirage-www locally and got distracted by new variables REDIRECT and HOST; is there already a summary of their semantics somewhere?  If not I can puzzle it out from config and dispatch and write one up. (@samoht?)

**Comment by samoht** [comment]
err no sorry I haven't written anything about them yet. If you have the time to draft that, that would be very helpful! Thanks!

**Comment by mor1** [comment]
This looks to me like it can be closed now -- @djs55 any objections?

**Comment by djs55** [comment]
The doc is much better now, thanks!
