### ISSUE TITLE
Add a page that lists breaking changes

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#339]
via @talex5 on the [mailing list](http://lists.xenproject.org/archives/html/mirageos-devel/2015-06/msg00132.html)

> This reminded me (as I mentioned yesterday) that we've made several
breaking API changes recently, and it would be very nice if there were
a page on the web-site listing breaking API changes, saying:

> 1. What the change is.
> 2. What error you are likely to see.
> 3. How to update your code.

> (this should include cases where the user just needs to rerun "mirage
configure")

We do note breaking changes in the `changes` files of repos but there's a good point that aggregating a list of them in one place would be really useful. To do this reliably would require some form of automation but it's not clear how we would achieve that.

One option (discussed on the dev call) was to extract those elements from the changes files, but this seems quite brittle as we don't already have a consistent practice around this.

Thoughts are welcome!

**Comment by dsheets** [comment]
We should adopt a consistent practice around this (as well as `CHANGES` formatting in general). [avsm/opam-repo-tools](https://github.com/avsm/opam-repo-tools) has an embryonic changelog parser but we may want to start over. We should build change log parsing and checking into our automation and additionally adopt a way to reference code identifiers which can be automatically linked to the relevant documentation/source when the changelog is rendered to hypertext.

**Comment by talex5** [comment]
I think we might want to write more user-friendly entries than just scraping changelogs.
If we want people to use mirage in production, this is something we need to do well.

Anyway, I've made a PR with an example entry here: https://github.com/mirage/mirage-www/pull/340

**Comment by dsheets** [comment]
I agree that there is a need for drafting good, user-friendly change documentation to help people migrate their code. That would be complementary to changelog automation.

**Comment by samoht** [comment]
This is now online at http://openmirage.org/wiki/breaking-changes

**Comment by amirmc** [comment]
We still need to come up with an automated way of dealing with this in future.  Ideally, we should only have to note/document such changes in one place and have content update by magic.
