### ISSUE TITLE
Socket config currently ignored

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#344]
My usual process is to use the following, which builds just fine.
```
env NET=socket PORT=8080 mirage configure --unix
```

But running it doesn't work.
```
AmirMacBook:src amir$ ./mir-www
Manager: connect
Manager: configuring
Manager: socket config currently ignored (TODO)
Listening on http://localhost/
Fatal error: exception Unix.Unix_error(Unix.EACCES, "bind", "")
Raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 105, characters 2-77
```

**Comment by avsm** [comment]
Preface it with sudo

**Comment by talex5** [comment]
Looks like the port is now hard-coded to 80 in `dispatch.ml`:

https://github.com/mirage/mirage-www/blob/0da4898b16e9efcd0c322dcc2984a49d87a9d37b/src/dispatch.ml#L216

**Comment by amirmc** [comment]
> Preface it with sudo

Face, meet Palm.  Palm, this is face.  I'm sure you'll get on great together.

(Thanks, folks. now working)
