### ISSUE TITLE
Only the master branch should be pushed live

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-www#347]

**Comment by samoht** [comment]
See https://github.com/ocaml/ocaml-travisci-skeleton/commit/7950dd2a11aa69e55b3393bd279a5ae7ca1da8de for a broken tentative at fixing this

**Comment by Drup** [comment]
since you are using travis, why not just use the `$TRAVIS_BRANCH` env variable ?

**Comment by samoht** [comment]
err ... sounds like a good idea :-)

**Comment by Drup** [comment]
Personally, I also do [that](https://github.com/Drup/LILiS/blob/master/.travis-ci.sh#L38) so that it doesn't try to deploy if it's a fork with CI enabled ....
