### ISSUE TITLE
Large variations in ping times

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-www#352]
```
$ ping mirage.io
PING mirage.io (46.43.42.146): 56 data bytes
64 bytes from 46.43.42.146: icmp_seq=0 ttl=25 time=33.236 ms
64 bytes from 46.43.42.146: icmp_seq=1 ttl=25 time=26.304 ms
64 bytes from 46.43.42.146: icmp_seq=2 ttl=25 time=27.664 ms
64 bytes from 46.43.42.146: icmp_seq=3 ttl=25 time=534.004 ms
64 bytes from 46.43.42.146: icmp_seq=4 ttl=25 time=452.165 ms
64 bytes from 46.43.42.146: icmp_seq=5 ttl=25 time=675.192 ms
64 bytes from 46.43.42.146: icmp_seq=6 ttl=25 time=35.132 ms
64 bytes from 46.43.42.146: icmp_seq=7 ttl=25 time=36.495 ms
64 bytes from 46.43.42.146: icmp_seq=8 ttl=25 time=679.709 ms
64 bytes from 46.43.42.146: icmp_seq=9 ttl=25 time=27.912 ms
64 bytes from 46.43.42.146: icmp_seq=10 ttl=25 time=882.900 ms
64 bytes from 46.43.42.146: icmp_seq=11 ttl=25 time=30.289 ms
Request timeout for icmp_seq 12
64 bytes from 46.43.42.146: icmp_seq=13 ttl=25 time=331.331 ms
64 bytes from 46.43.42.146: icmp_seq=12 ttl=25 time=1335.252 ms
64 bytes from 46.43.42.146: icmp_seq=14 ttl=25 time=28.799 ms
64 bytes from 46.43.42.146: icmp_seq=15 ttl=25 time=38.447 ms
```

**Comment by djs55** [comment]
Maybe a cause: the console is very busy with traffic like

```
200 GET /css/font-awesome.css
200 GET /js/vendor/custom.modernizr.js
200 GET /js/vendor/jquery.min.js
200 GET /js/foundation/foundation.min.js
200 GET /js/foundation/foundation.topbar.js
200 GET /js/vendor/highlight.pack.js
200 GET /graphics/mirage-logo-small.png
200 GET /graphics/pinata_access.png
200 GET /graphics/cloud-bg.png
Tcp.Segment: TCP retransmission on timer seq = 452895699
conn 6669 closed
Tcp.Segment: TCP retransmission on timer seq = 452891750
conn 6513 closed
conn 6515 closed
conn 6516 closed
conn 6512 closed
conn 6514 closed
[104.192.218.186:55307] TLS eof
conn 6499 closed
Tcp.Segment: TCP retransmission on timer seq = 452897159
Listening on https://mirage.io/
301 REDIRECT https://mirage.io
conn 6714 closed
Tcp.Segment: TCP retransmission on timer seq = 452893210
```

**Comment by samoht** [comment]
The console outputs are supposed to be asynchronous. Is there a way to get the number of lines waiting to be printed on the console, or maybe we should discard console lines with there is too much pressure?

**Comment by djs55** [comment]
You're right -- `Console.log` looks like it will truncate rather than
block. It must be blocking somewhere else, causing the ping time problem.

On Tue, Jun 30, 2015 at 10:41 AM, Thomas Gazagnaire <
notifications@github.com> wrote:

> The console outputs are supposed to be asynchronous. Is there a way to get
> the number of lines waiting to be printed on the console, or maybe we
> should discard console lines with there is too much pressure?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/issues/352#issuecomment-117095605>.
>



-- 
Dave Scott

**Comment by djs55** [comment]
Interestingly in `xentop` when this happens:

```
64 bytes from 46.43.42.146: icmp_seq=53 ttl=20 time=30.256 ms
Request timeout for icmp_seq 55
Request timeout for icmp_seq 56
64 bytes from 46.43.42.146: icmp_seq=54 ttl=20 time=3500.285 ms
64 bytes from 46.43.42.146: icmp_seq=55 ttl=20 time=2496.596 ms
64 bytes from 46.43.42.146: icmp_seq=56 ttl=20 time=1491.539 ms
64 bytes from 46.43.42.146: icmp_seq=57 ttl=20 time=487.433 ms
64 bytes from 46.43.42.146: icmp_seq=58 ttl=20 time=30.394 ms
```
the domain's CPU spikes to 70%-- it looks like it's doing something
CPU-bound which is starving the ethernet layer?

On Tue, Jun 30, 2015 at 11:47 AM, David Scott <scott.dj@gmail.com> wrote:

> You're right -- `Console.log` looks like it will truncate rather than
> block. It must be blocking somewhere else, causing the ping time problem.
>
> On Tue, Jun 30, 2015 at 10:41 AM, Thomas Gazagnaire <
> notifications@github.com> wrote:
>
>> The console outputs are supposed to be asynchronous. Is there a way to
>> get the number of lines waiting to be printed on the console, or maybe we
>> should discard console lines with there is too much pressure?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mirage/mirage-www/issues/352#issuecomment-117095605>.
>>
>
>
>
> --
> Dave Scott
>



-- 
Dave Scott

**Comment by samoht** [comment]
Can the RRDs be causing something like that?

**Comment by talex5** [comment]
Even if `Console.log` doesn't block, it will still fill up the buffer, which may cause other callers (using `log_s`) to block.

How about compiling it with tracing on? Then we can see what it's doing with mirage-trace-viewer (or, what it was doing, if it crashes or hangs). Tracing does have some overhead though, so if we can reproduce the problems on a test instance that would be ideal.

Note: `mirage-www`'s `config.ml` has a commented out line requesing a 10K trace buffer. I would suggest increasing this to about 1M if you want anything useful.

**Comment by samoht** [comment]
@talex5 can you create a PR to enable traces on mirage-www?

**Comment by yomimono** [comment]
@samoht Do I remember correctly that you had to use FAT and a filesystem to host the keys?  If that's the case, mightn't this be our first time using these modules to host the site?

I'm building mirage-www (with a selfsigned cert) locally and hope to get some useful traces out of it, but it just occurred to me that I'm doing this with crunch and so it may not be a good mirror of the site as it's running.

**Comment by yomimono** [comment]
I can see variable (sub-ms to hundred+-ms) ping delays running the unikernel locally, and high CPU usage in xentop.  Both vary in the obvious way with the number of incoming requests.  [A trace is available](http://yomimono.org/tls_out.ctf) if anyone's interested; I haven't yet looked at it but plan to.

**Comment by talex5** [comment]
@samoht https://github.com/mirage/mirage-www/pull/354

**Comment by talex5** [comment]
@yomimono looks like it's spending half its time on lots and lots of small GC runs. Is this part of the TCP debug settings, or does it just need more memory?

BTW, we should apply your patch https://github.com/mirage/mirage-tcpip/pull/156 too, to get rid of those exceptions.

**Comment by samoht** [comment]
> @samoht Do I remember correctly that you had to use FAT and a filesystem to host the keys? If that's the case, mightn't this be our first time using these modules to host the site?

yes, the certificates are stored on a (very small) FAT filesystem.

**Comment by samoht** [comment]
hum, it seems that mirage-www is reloading (and parsing) all the webpages on each query.... might explain why it's becoming slow...

**Comment by avsm** [comment]
That would destroy the performance indeed!
