### ISSUE TITLE
Some kind of mouse offset issue with the stats visualisation

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#357]
Hard to get a screenshot as it depends on the mouse position but here's how to repo:
- Go to the stats page at https://mirage.io/stats/gc?timescale=minute
- Hover over a certain time point to get detailed values at that time point
- Notice that the actual data (and marker) is some way _to the right_ of the actual cursor
- Move the cursor left and right and observe that it's some kind of scaling effect i.e. there's no delta between cursor location and marker at the origin, but the delta increases linearly as you move to the right.

cc @djs55 @samoht

**Comment by djs55** [comment]
This is [djs55/ocaml-c3#8] -- I've not had time to investigate it yet. I
need to reproduce it with pure c3 in .js, and if it reproduces there I can
file a bug upstream.

On Tue, Jun 30, 2015 at 5:26 PM, Amir Chaudhry <notifications@github.com>
wrote:

> Hard to get a screenshot as it depends on the mouse position but here's
> how to repo:
>
>    - Go to the stats page at https://mirage.io/stats/gc?timescale=minute
>    - Hover over a certain time point to get detailed values at that time
>    point
>    - Notice that the actual data (and marker) is some way *to the right*
>    of the actual cursor
>    - Move the cursor left and right and observe that it's some kind of
>    scaling effect i.e. there's no delta between cursor location and marker at
>    the origin, but the delta increases linearly as you move to the right.
>
> cc @djs55 <https://github.com/djs55> @samoht <https://github.com/samoht>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/issues/357>.
>



-- 
Dave Scott

**Comment by yomimono** [comment]
I just noticed this happening when looking at the stats yesterday, so it's still an issue.

**Comment by hannesm** [comment]
Closing, the stats has been removed when the website rework was done (for MirageOS4).
