### ISSUE TITLE
Add blog post describing the stats page

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#363]
Following on from #350.

@djs55 have you had a chance to have a go at this?

**Comment by hannesm** [comment]
I think response times would be great to include in the statistics.

**Comment by samoht** [comment]
@djs55 ping? :-) also would be great to release the stats as a separate library, this can be used by other websites such as [canopy](http://canopy.mirage.io/) /cc @Engil (see https://mirage.io/stats/gc and https://github.com/mirage/mirage-www/tree/master/stats)

**Comment by hannesm** [comment]
Closing, since the stats pages are gone now.

**Comment by TheLortex** [comment]
Note that I have worked on adding a metrics endpoint that we could use for monitoring: https://github.com/mirage/mirage-www/pull/714
