### ISSUE TITLE
Inconsistent prefixing for command line invocation

### ISSUE THREAD

**Issue by dongcarl** [mirage/mirage-www#365]
In https://github.com/mirage/mirage-www/blob/ff3dd44e38ccd873454d5eb07ec4383c50e126f0/tmpl/wiki/hello-world.md, some command line invocations are prefixed by "$ ", and some are not. Is there a reason for this?

**Comment by avsm** [comment]
Traditionally this is to indicate a command that is either root (`#`) or a normal user (`$`).  It's almost certainly inconsistent here though...

**Comment by dongcarl** [comment]
@avsm Haha yes I knew that... Perhaps I'll make a pull request making everything "$ " sometime...
