### ISSUE TITLE
contributing.md: broken link to opam docs

### ISSUE THREAD

**Issue by moonlightdrive** [mirage/mirage-www#366]
On the [contributing](https://mirage.io/wiki/contributing) page, this link is broken:

> If you are making code changes, you may wish to point `opam` to your local repository for that code with `opam pin`. [More details on using opam when developing are available at the `opam` site.](https://opam.ocaml.org/doc/Developing.html)

Not sure if you want it to point here? http://opam.ocaml.org/doc/1.1/Developing.html
I cannot find an equivalent page in the 1.2 docs

**Comment by mor1** [comment]
I guess <https://opam.ocaml.org/doc/Packaging.html#Sometricks> or even
just  <https://opam.ocaml.org/doc/Packaging.html>?

On 11 July 2015 at 22:17, Jyotsna <notifications@github.com> wrote:

> On the contributing <https://mirage.io/wiki/contributing> page, this link
> is broken:
>
> If you are making code changes, you may wish to point opam to your local
> repository for that code with opam pin. More details on using opam when
> developing are available at the opam site.
> <https://opam.ocaml.org/doc/Developing.html>
>
> Not sure if you want it to point here?
> http://opam.ocaml.org/doc/1.1/Developing.html
> I cannot find an equivalent page in the 1.2 docs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/issues/366>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by avsm** [comment]
@mor1 any chance of a pull req with those urls?  They sound right.

**Comment by mor1** [comment]
done; https://github.com/mirage/mirage-www/pull/387  will merge when travis goes green
