### ISSUE TITLE
Where is .travis-www.ml?

### ISSUE THREAD

**Issue by moonlightdrive** [mirage/mirage-www#368]
Hi, I was hoping to take a look at this file referenced by both [Deploying via CI](https://mirage.io/wiki/deploying-via-ci) and [Building the website](https://mirage.io/wiki/mirage-www).

Apparently it was here: https://github.com/mirage/mirage-www/blob/master/.travis-www.ml, but where is it now? Thanks!

**Comment by samoht** [comment]
It is now here: https://github.com/ocaml/ocaml-travisci-skeleton/blob/master/travis_mirage.ml

**Comment by mor1** [comment]
Closing as I've updated the intro pages, including both of those referenced so hopefully there aren't any dangling links now. Please reopen if I missed something!
