### ISSUE TITLE
The regexp guide

### ISSUE THREAD

**Issue by Drup** [mirage/mirage-www#371]
There is a regexp guide here: https://mirage.io/wiki/ocaml-regexp

It seems outdated and I'm not sure what it aims to achieve, it does a lot of arguing and not a lot of teaching (and talk about a library that is not used in mirage). Should it be removed ? renovated ? If the later, how ?

**Comment by Drup** [comment]
FWIW, by pure curiosity, I added Re to the benchmark [here](https://github.com/Drup/regexp-benchmark) (the execution beats everyone, but str parsing seems a bit slow).

**Comment by dbuenzli** [comment]
Destroy it. Most programmers use regexps for wrong purposes.

**Comment by Drup** [comment]
Well, that's beside the point. The question is more if it's useful to use mirage, and I don't feel like it is.

**Comment by dsheets** [comment]
I think it's useful to point out that you can't use `Str` for regexps for true Mirage apps for a variety of reasons. Outlining the alternatives is also useful. The graph is pretty bad and some of the text could be cleaned, though.

**Comment by dbuenzli** [comment]
Well there are a lot of libraries you can't use on Mirage for a variety of reasons, are you going to make a webpage for each of them ?

**Comment by dsheets** [comment]
No, but `Str` is surprising given its functionality is purely functional. If there are other surprisingly incompatible libraries then, yes, I would advocate documentation about why they are incompatible and suggestions of alternatives or projects working on fixes.

**Comment by dbuenzli** [comment]
> I would advocate documentation about why they are incompatible and suggestions of alternatives or projects working on fixes.

Yes, a general webpage and sniffing guidelines for this seems more sensible.

**Comment by mor1** [comment]
On 21 July 2015 at 18:34, Daniel Bünzli <notifications@github.com> wrote:

> I would advocate documentation about why they are incompatible and
> suggestions of alternatives or projects working on fixes.
>
> Yes, a general webpage and sniffing guidelines for this seems more
> sensible.
>
+1 particularly to the "sniffing guidelines" (if by that you mean
guidelines about how to determine whether or not a library is appropriate
to use with Mirage, and what to do about it).

Moar Power To The People and all that.

-- 
Richard Mortier
mort@cantab.net

**Comment by samoht** [comment]
+1 for kill it

**Comment by talex5** [comment]
Could we put a date on it (for when it was written) and mark it as a blog post instead of a wiki page? It may have some historical interest, but it's not current documentation. We could do to the same to https://mirage.io/wiki/delimcc-vs-lwt too.

**Comment by yomimono** [comment]
I'm fine with killing both of these articles; datestamping them and moving them to the blog would be okay too.  (I get the feeling that the delimcc-vs-lwt article is of more potential historical interest and might benefit from this.)

Perhaps we should do that and open a new issue asking for an article or post about determining whether a library will be easy to use with Mirage.

**Comment by avsm** [comment]
Moving them to a blog post would be best; they do have historical use.
