### ISSUE TITLE
is mirage broken is out of date

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#374]
this shows information from november 2014: https://mirage.io/wiki/is-mirage-broken ... some automation to get this in sync with reality would be great!

**Comment by amirmc** [comment]
The actual logs are at: https://github.com/mirage/is-mirage-broken/blob/master/logs/README.md

Some automation at build time to grab the correct input file seems like one approach.

(sidenote: is-mirage-broken isn't looking to happy at the moment)
