### ISSUE TITLE
Infrastructure: Split out the ARM build from the is-mirage-broken

### ISSUE THREAD

**Issue by dsheets** [mirage/mirage-www#375]
I don't know if this is the right repo to report to. Correct me and I'll go post elsewhere.

**Comment by amirmc** [comment]
Any report is a good report.  This is still down so I'm going to email the list about it.

**Comment by avsm** [comment]
From the mailing list:
> The VM at Rackspace had both rebooted and the Docker volume had run out of disk space since we don't garbage collect the is-mirage-broken cron job volumes.  I've installed a cron job to reap intermediate containers now, which should alleviate the situation.
> In the longer term, I'm looking into moving the Docker cron jobs into a more dedicated infrastructure, instead of repurposing the ARM build VM.  I'll update the bug report to reflect this and leave it open.
