### ISSUE TITLE
Consider other video call options for the fortnightly video calls

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#392]
This was brought up on the [mailing list][1], so we should take another look at what's out there.  I asked people to email me directly, so as to avoid a lengthy, tangential discussion on the mailing list.  However, I decided to move this to an issue so there's more transparency about the discussions.

Just to set expectations, we'll be sticking with Google Hangout for the time being.

[1]: http://lists.xenproject.org/archives/html/mirageos-devel/2015-09/msg00092.html

**Comment by amirmc** [comment]
*from @talex5 on the email thread*: 

> Personally, I thought Hangouts worked pretty
well. We seem to get more people joining the hangouts than we do when
we use GotoMeeting, I don't need to run a Windows VM to join, and the
picture quality is better. The need for a Google account and
installing a plugin is annoying, though.

In principle, I’d agree but not everyone who joins the Hangout is there for the call (occasionally, random G+ folks would also join — and leave pretty quickly).  Apart from the need for a Google account, it's the best (free) option I've come across.

**Comment by amirmc** [comment]
Two other suggestions were:

- Jitsi - https://jitsi.org (open source, one positive review)

- BlueJeans (paid for) - http://bluejeans.com (I had one person tell me that Hangouts were better than this, though)

**Comment by Chris00** [comment]
The [comparison](https://en.wikipedia.org/wiki/Comparison_of_web_conferencing_software) may be a good starting point.  Some software that may be worth investigating:
- [Ring](http://ring.cx/?utm_content=buffera83e0&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer)
- [Blink](http://www.icanblink.com/)
- [Apache OpenMeetings](https://openmeetings.apache.org/)

**Comment by hannesm** [comment]
I've successfully used and am quite happy with [mumble](http://wiki.mumble.info/wiki/Main_Page): it needs a server, and you've to use push-to-talk. it's audio only, but completely open source and runs even on marginalised operating systems such as FreeBSD ;)

**Comment by Drup** [comment]
For all those, I think the absence of a web interface is an issue (this is why I like jitsi, especially since it doesn't need chrome/a plugin).

@hannesm : mumble works fine on voice-activation. ;)

**Comment by amirmc** [comment]
I haven't had a chance to explore any of these since last week.  Would anyone have time to help me test some of these out over the next week or so?

(cc @yomimono, as she was also on the mailing list thread).

**Comment by dbuenzli** [comment]
> https://meet.jit.si/

If this works it looks like a dream it seems you don't even need an account. 

> Would anyone have time to help me test some of these out over the next week or so?

I can.

**Comment by Drup** [comment]
I can too, to test with someone (a bit) further away.

**Comment by amirmc** [comment]
A few of tried an impromptu experiment with https://meet.jit.si/ yesterday afternoon (most of us were in Cambridge, all of us were in the UK).

Overall, it seemed to work reasonably well.  There was a mix of hardware but we primarily used Firefox and Chrome.  It seems as though there may be issues with the picture-in-picture on Firefox but it did seem that everyone could hear each other. Screen-sharing worked (though it's not a feature we've needed before) and the chat feature also seemed fine.  A few people had to install a browser plugin of sorts, but I don't recall that being necessary in Chrome (though it could have happened in the background).  Beyond that, there was no need for accounts or installation of software.

I'd like to try another experiment today but with more people, including those further away.  I suggest that we spend 10mins straight after today's Mirage call, since many of us will be available. 

@Drup @dbuenzli Would you be able to join in?  It would likely be around 16:30/16:40 BST (that's typically when we wrap up the Mirage Calls).

**Comment by mor1** [comment]
On 14 October 2015 at 11:52, Amir Chaudhry <notifications@github.com> wrote:

> A few people had to install a browser plugin of sorts, but I don't recall
> that being necessary in Chrome (though it could have happened in the
> background).


FFox required a plugin for screen sharing, but not for anything else.
Didn't try screen sharing on Chrome.


-- 
Richard Mortier
richard.mortier@cl.cam.ac.uk

**Comment by Drup** [comment]
> @Drup @dbuenzli Would you be able to join in? It would likely be around 16:30/16:40 BST (that's typically when we wrap up the Mirage Calls).

I'm available to test it yes, just ping me on IRC.

**Comment by amirmc** [comment]
Great! @pqwy is also happy to join and boost numbers.

**Comment by amirmc** [comment]
We tried Jitsi out again after the last MirageOS call and it worked as well as previously.  The biggest feature was the ease of getting into the call (no login, account required).  This was sufficiently good that the people on the call agreed that we should just switch to using this system instead of Google Hangout.  

It didn't seem worth trying out all the other options since this worked well enough.  I'll email the list soon and let people know.

**Comment by amirmc** [comment]
We used Jitsi for the last call and it went pretty well.  Unless anything drastic happens on the next call (tomorrow), we'll stick with this option for the foreseeable future.  Closing this issue now.
