### ISSUE TITLE
Small race in the deploy script

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-www#408]
When pushing the final deployment image, `openmirage.org` and `mirage.io` both compete to push to the same branch. Usually the builds do not take the same time, so the race rarely happens and both pushes are successful, but sometime the race happens:

```
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.
To git@mir-deploy:mirage/mirage-www-deployment
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@mir-deploy:mirage/mirage-www-deployment'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
'OPAMYES=1 export OPAMYES; MIRDIR=${MIRDIR:-src} export MIRDIR; XENIMG=mir-${XENIMG:-$TRAVIS_REPO_SLUG#mirage/mirage-}.xen export XENIMG; DEPLOYD=${TRAVIS_REPO_SLUG#*/}-deployment export DEPLOYD; set -ex; cd $DEPLOYD && git add xen/$TRAVIS_COMMIT xen/latest && git commit -m "adding $TRAVIS_COMMIT for $MIRAGE_BACKEND" && git push' exited 1. Terminating with 1
```

**Comment by samoht** [comment]
Maybe just adding the right `git rebase` runes just before [pushing](https://github.com/ocaml/ocaml-ci-scripts/blob/master/travis_mirage.ml#L104) is enough. /cc @mor1

**Comment by mor1** [comment]
That sounds very plausible -- at least it should dramatically reduce the window of opportunity for the conflict to occur.

**Comment by mor1** [comment]
Attempted fix in PR https://github.com/ocaml/ocaml-ci-scripts/pull/111

**Comment by mor1** [comment]
In discussion with @avsm the thought also occurs that we could 
+ remove the redirect logic from here altogether, 
+ build only the `mirage.io` version, and
+ run a separate (containerised?) instance of https://github.com/mor1/http2https (eg., https://hub.docker.com/r/mor1/mir-http2https/ after a suitably parameterised rebuild)

Thoughts?

**Comment by samoht** [comment]
That seems like a good idea. I guess we don't really want to change the redirector too often anyway.

**Comment by samoht** [comment]
Closing this as I merged the small hack to make the race condition smaller. Having a proper redirector is a longer term plan, please track that in a separate issue.
