### ISSUE TITLE
2015 year-in-review blogpost

### ISSUE THREAD

**Issue by yallop** [mirage/mirage-www#415]
Incorporate notes on 

* [ ] Papers published
* [ ] Releases
* [ ] Talks, demos and other events
* [ ] Press/media
* [ ] Blog posts (both on mirage-www and elsewhere) and HN discussions
* [ ] New users and uses
* [ ] New contributors
* [ ] Interesting PRs and commits
* [ ] Related developments (OPAM, OCaml, RPI, js_of_ocaml etc.)
* [ ] Upcoming features
* [ ] Anything else?

**Comment by avsm** [comment]
That looks like a solid list to start with!

**Comment by hannesm** [comment]
I assume this can be closed (due to being out of date, and publishing a year-in-review in the middle of the year is not worth it).  Certainly there should be somewhere a 3.0-release post... but not in this issue
