### ISSUE TITLE
Regarding mini-os bootup

### ISSUE THREAD

**Issue by pkm2kor** [mirage/mirage-www#419]
Hi,
I am facing problem during mini-os boot-up. The execution breaks while checking for fdt_check_header while calling fdt32_to_cpu. I think it is not able to use the address of the dtb provided during arch_init.
The address i can see is 0x08400000.

(d3) Virtual -> physical offset = 3fc00000
(d3) Checking DTB at 08400000...
(d3) Fault handler at 004081ac called (prefetch_abort)

after this it dumps registers.

Any pointers will be of great help.

Thanks,
Pankaj

**Comment by avsm** [comment]
This is an ARM device I assume -- which one?

**Comment by pkm2kor** [comment]
Its odroid xu4.

**Comment by pkm2kor** [comment]
HI Anil,

Sorry for my questions...

I am not understanding have we specified the address of dtb, and first of all we have not compiled any dtb with mini-os, so which dtb will be used here ?

**Comment by talex5** [comment]
Probably best to ask on the [Mini-OS list](http://lists.xenproject.org/cgi-bin/mailman/listinfo/minios-devel). Xen should be setting the r2 register itself before starting Mini-OS.

**Comment by pkm2kor** [comment]
Thanks Thomas.
We have not appended ant dtb to mini-os image. this means that xen will provide dtb info. right?

**Comment by talex5** [comment]
Should do I think, though I don't know much about it. Is the whole DTB unreadable, or is it going wrong while scanning it? You could try modifying arm32.S to read the first word immediately, in case there's something wrong with the memory mapping.

e.g. `ldr r10, [r2]` at the start of `_reset` to put the first word of the DTB into `r10`, then move it into `r2` (`mov r2, r10`) just before `arch_init` so the C code receives it as an extra argument.

**Comment by pkm2kor** [comment]
In the function "libxl__arch_domain_init_hw_description", where DTB is created by xen tools, i am able to dereference the pointer & call fdt_check_header(fdt) returns 0 i.e. it succeeds (i modified the above function and added the code to do this check).
I think after the DTB is copied to new location it is not accessible in arch_init function.

**Comment by talex5** [comment]
If you add the `ldr` I mentioned above, does it crash immediately on boot (the DTB is inaccessible at boot) or does it still get to `arch_init`?

**Comment by pkm2kor** [comment]
It crashes on ldr also.
