### ISSUE TITLE
Race condition in Travis deploy scripts?

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#422]
I *think* there's a race condition in the deploy scripts that push to `mirage-www-deployment`.  We currently build and deploy two unikernels and Travis does these in parallel. I just saw the following build failure for the `mirage.io` Xen build (in build number `#1001` — I restarted it so the full log might be lost now).  I did notice that the deployment repo had a new successful push for one of the unikernels.

@mor1 @samoht Am I right about the above? Apart from restarting the failed build, is there anything else we could do?  I'm wondering about future scenarios where we might want to build/deploy for multiple backends but still push each one into the same repo.

```
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.
To git@mir-deploy:mirage/mirage-www-deployment
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@mir-deploy:mirage/mirage-www-deployment'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by samoht** [comment]
Indeed, see #408

**Comment by amirmc** [comment]
Aha, thanks. Closing this as a dupe.
