### ISSUE TITLE
Blog post on Solo5/MirageOS

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#425]
See recent thread on the mailing list.

http://lists.xenproject.org/archives/html/mirageos-devel/2016-01/msg00007.html

**Comment by amirmc** [comment]
@djwillia did the work and the repo is at https://github.com/djwillia/solo5/tree/mirage.
An intro post would reach a wider audience and generate more feedback :)

**Comment by djwillia** [comment]
Not sure if I did the pull request thing correctly.... Let me know if you have comments on the post!  Thanks!
