### ISSUE TITLE
mirage-www doesn't set the proper content header for svg files

### ISSUE THREAD

**Issue by Drup** [mirage/mirage-www#436]
Apparently, `svg` files are not given the proper content header, which causes issues under safari. I guess magic-mime would solve the issue.

**Comment by mor1** [comment]
Chromium also -- it seems that they render when I click on them, but when rendered inline they break.

**Comment by amirmc** [comment]
Same on iOS (Safari and Chrome).

Seems to work fine in Firefox (on OS X).

**Comment by samoht** [comment]
This needs a patch to cowabloga, I'm working on it

**Comment by Drup** [comment]
Thanks!

**Comment by samoht** [comment]
TravisCI is sooo long today. Should be fixed when https://travis-ci.org/mirage/mirage-www/builds/112602442 is complete

**Comment by amirmc** [comment]
It looks like that build failed. See https://travis-ci.org/mirage/mirage-www/jobs/112602446

```
File "wiki.ml", line 33, characters 2-21:
Error: This function has type
         content:('a Cow.Xml.frag as 'a) list Lwt.t ->
         sidebar:('b Cow.Xml.frag as 'b) list -> Cow.Xml.t Lwt.t
       It is applied to too many arguments; maybe you forgot a `;'.
Command exited with code 2.
```

**Comment by samoht** [comment]
https://github.com/mirage/mirage-www/pull/437

**Comment by samoht** [comment]
Fixed. https://mirage.io/blog/introducing-functoria now displays pretty images

**Comment by amirmc** [comment]
Yay! \o/
