### ISSUE TITLE
Dead link on wiki/xen-boot.

### ISSUE THREAD

**Issue by mmaker** [mirage/mirage-www#440]
At https://mirage.io/wiki/xen-boot I read 
"There is a script in scripts/xcp.sh that takes a kernel.xen output from MirageOS and makes the appropriate API and SSH calls. Thanks to Mike McClurg from Citrix for contributing this script."

But `https://github.com/avsm/mirage/tree/master/scripts/xcp.sh` is a dead link.

**Comment by yomimono** [comment]
Very belated thanks for the issue submission.  The `xen-boot` page generally needs some attention -- I think @acw has a much nicer deployment story for unikernels on EC2 (although I'm not sure where it lives), and we're probably safe to remove the instructions that reference Xen 4.1 (!).

**Comment by acw** [comment]
It lives here: https://github.com/GaloisInc/ec2-unikernel

Bug reports, feature requests, etc., etc. are very much appreciated.

**Comment by yomimono** [comment]
Awesome, thank you!!

On July 22, 2016 6:42:31 PM GMT+01:00, Adam Wick <notifications@github.com> wrote:
>It lives here: https://github.com/GaloisInc/ec2-unikernel
>
>Bug reports, feature requests, etc., etc. are very much appreciated.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mirage/mirage-www/issues/440#issuecomment-234608557

-- 
Composed on a touchscreen keyboard; please forgive typos and brevity.

**Comment by yomimono** [comment]
A scant 11 months after the initial report, this is fixed in e7962065edf7543d6d69e1bba9f20955c923cc81 .
