### ISSUE TITLE
'Frequently asked questions' is outdated

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-www#442]
Particularly the section `Q: Is MirageOS 1.0 'production ready'` stands out. 2.0 is out, TLS is implemented, and 2014 isn't in the future anymore.

I'm afraid I haven't kept up with the project to update it myself.

https://mirage.io/wiki/faq

**Comment by yomimono** [comment]
#455 is an attempt to make the FAQ less outdated -- thanks for filing this issue to get more eyes on it.  If you have any suggestions for more stuff to put in there, I'd be happy to include them as well!

**Comment by yomimono** [comment]
Closed via #455 . Thanks again!
