### ISSUE TITLE
Deployment issue of 04/05/2016

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-www#448]
Just to remember the issues I've hit and need to be fixed:
- [ ] https://github.com/mirage/mirage/issues/517
- [ ] https://github.com/mirage/mirage-net-xen/issues/39
- [x] https://github.com/mirage/mirage-www/issues/408
- [ ] @jonludlam I had to destroy your `jon` VM as it was using the IP address reserved for `mirage.io`. Please update its configuration.

**Comment by hannesm** [comment]
you also hit https://github.com/mirage/mirage/issues/517 (and needed to pass `--network 0` to `mirage configure`...

**Comment by samoht** [comment]
isn't it already in the list? :p

**Comment by hannesm** [comment]
ups, i shouldn't type while sleeping... 4 hours ago...

**Comment by samoht** [comment]
the workaround I've put in place:
- [pin mirage-net-xen to 1.4.2](https://github.com/mirage/mirage-www/commit/002e036ce6da4a85283f43b8f90e3f9c7c4d548e)
- [add a --network command-line argument](https://github.com/mirage/mirage-www/commit/c60320e282d700a98abfb37a26d7b8ae09f1f08a)
- restarted the failed TravisCI job
- `xl destroy jon` on the deployment machine (sorry @jonludlam you might have to restart your VM)

**Comment by hannesm** [comment]
...and again a travis race after your most recent merge...

**Comment by samoht** [comment]
Build restarted...

**Comment by samoht** [comment]
@jonludlam ?

**Comment by hannesm** [comment]
I'm closing this.  mirage#517 was addressed and is closed now, as is mirage-net-xen#39.  our website is also up and running right now :)
