### ISSUE TITLE
mirage.io's TLS certificate is expired

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-www#451]
```
The certificate expired on 05/05/2016 12:59 AM. The current time is 05/05/2016 09:56 AM.
```

Paging @avsm , who I think mentioned getting a Let's Encrypt cert instead of renewing with our previous CA.

**Comment by yomimono** [comment]
Resolved by @avsm (thanks!) . Details at http://lists.xenproject.org/archives/html/mirageos-devel/2016-05/threads.html under "Expiration of the certificate SSL Standard (mirage.io)".

**Comment by hannesm** [comment]
details online on canopy: http://canopy.mirage.io/Wiki/Letsencrypt :+1: (using the DNS challenge)

**Comment by avsm** [comment]
added a pioneer project for good measure; I love Letsencrypt! https://github.com/mirage/mirage-www/wiki/Pioneer-Projects#letsencrypt-compliant-dns-server
