### ISSUE TITLE
dead link in functoria blogpost

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#456]
https://mirage.io/blog/introducing-functoria says

The complete example is available in mirage-skeleton in the `app_info` directory.

@Drup I can't find the app_info stuff... care to put it into the mirage-skeleton repository please? :)

**Comment by Drup** [comment]
I'm absolutely sure that I wrote it, but I can't find it anymore. I'll rewrite it quickly, do you want a webpage version of a console-only version ?

**Comment by hannesm** [comment]
if you ask, both :)

**Comment by yomimono** [comment]
@drup - could you give us something to go on for recreating this?

**Comment by Drup** [comment]
dammit, I forgot! It's here: https://github.com/mirage/mirage-skeleton/pull/167

**Comment by yomimono** [comment]
Looks good to me; now the user has something to play with! :)

**Comment by hannesm** [comment]
thanks for fixing this
