### ISSUE TITLE
mirage-www install instructions out of date

### ISSUE THREAD

**Issue by GemmaG** [mirage/mirage-www#467]
- [x]  min is ocaml 4.02.3 not 4.02.1
https://lists.xenproject.org/archives/html/mirageos-devel/2016-07/msg00013.html

### Requirements

* "MirageOS has been tested on ArchLinux, Debian Wheezy, Ubuntu Precise/Lucid/Raring/Saucy, CentOS 6.4 and MacOS X 10.8 and 10.9. To compile the Xen backend, you must have a 64-bit Linux host. 32-bit is not supported at this time."

- [x] Is this out of date information?

* The following points are specific to individual setups and can be separated/sectioned to make for easy, targeted reading:

- [x] "If you're using MacOS X 10.9 or older, you will also need the tuntap kernel module if you want to use the MirageOS network stack from userspace."

- [x] "If you're using Ubuntu/Debian, we recommend you also install the essential build tools (GNU make, etc) and GNU M4 as well as the OCaml toolchain including camlp4:

 apt-get install build-essential m4 ocaml ocaml-native-compilers camlp4-extra"

- [ ] "On CentOS 6.4, install the system compiler and libraries via:

 sudo yum groupinstall "Development Tools" "Development Libraries""

- [ ] "On Arch Linux, install the system compiler and libraries via:

 sudo pacman -S ocaml camlp4 ocaml-findlib
 yaourt -S opam"

### Using OPAM

* "Note that you require OPAM 1.2 or greater to use with MirageOS. Some distribution packages provide earlier versions and must be updated; check with

 $ opam --version ## response should be at least 1.2.0, viz.
 1.2.0"

- [x] Is this out of date? Could be under a subheading of versions? Or have it under requirements?

* "Next, make sure you have at least OCaml 4.01.0 or higher as your active compiler. This is generally the case on MacOS X, though Debian only has it in the unstable distribution at present. But don't worry: if your compiler is out of date, just run opam switch to have it locally install the right version for you.

- [x] Same as above point - can this be in a separate area - or under requirements?

**Comment by avsm** [comment]
partially fixed, need to address how to install opam 1.2.2 on debian stable (no packages available??) and also bring back CentOS 7...

**Comment by talex5** [comment]
opam 1.2.2 installs fine on Debian/stable for me:

```
~ $ docker run -it debian:stable /bin/bash
root@190a13e8b0dc:/# apt-get install ca-certificates 0install-core --no-install-recommends -y
root@190a13e8b0dc:/# 0install add opam http://tools.ocaml.org/opam.xml
root@190a13e8b0dc:/# opam --version
1.2.2
```

**Comment by avsm** [comment]
perfect, thanks @talex5! I'll recommend the use of 0install rather than a longwinded backport approach then.
