### ISSUE TITLE
List of Mirage libraries linked from mirage.io homepage

### ISSUE THREAD

**Issue by GemmaG** [mirage/mirage-www#491]
Add an up-to-date list of Mirage libraries to mirage.io. Ideally a tab at the top of the homepage that takes you to a curated list of libraries sectioned by type eg. use the tags on Canopy http://canopy.mirage.io/Projects (protocol, security) or similar.

Links with this: https://github.com/mirage/mirage/issues/569

**Comment by avsm** [comment]
Working on this via the TROVE file for mirage 3 (mirage/mirage#571) -- see also mirage/mirage#569

**Comment by amirmc** [comment]
> eg. use the tags on Canopy http://canopy.mirage.io/Projects (protocol, security) or similar

Would be much better if we could start using the opam metadata for this (e.g. the tag `org:mirage`).  We’ve discussed this a few times before but not really taken it much further.

**Comment by avsm** [comment]
Not linked from the homepage yet, but we have docs.mirage.io which is rebuilding documentation for packages. Will link it when its tested a little more.

**Comment by samoht** [comment]
The mirage libraries can be seen on https://ocaml.org/packages/search?q=tag%3A%22org%3Amirage%22 - we should probably add a link on https://mirage.io/docs to this

**Comment by samoht** [comment]
Actually "API" on the main page is pointing to https://docs.mirage.io which is already redirected to ocaml.org
