### ISSUE TITLE
can not load mirage image

### ISSUE THREAD

**Issue by byteshiva** [mirage/mirage-www#501]
I' getting cannont load mirage image. Can you let me know if i'm missing something here.. I have followed the installation instruction(using ubunt 14.10)

![image](https://cloud.githubusercontent.com/assets/10637299/20430567/0ee7fcca-adbb-11e6-8672-f89694fa1ace.png)

**Comment by yomimono** [comment]
It looks like you're running the Ubuntu-provided [mirage](http://packages.ubuntu.com/search?keywords=mirage) tool, which is an image viewer.  `apt-get remove mirage` to get rid of this tool (if you do use it, I can send you instructions on changing your `PATH` environment variable to make sure that the other `mirage` comes first, but that's a bit more involved).

Can you point us at the instructions you were following, so we can be sure to make this a bit clearer?
