### ISSUE TITLE
Blog post about improved/consistent dev workflow

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#511]
It'd be _really_ useful if someone were able to write a brief blog post in the next couple of weeks about the improvements to the dev workflow.  e.g. about things like `topkg`, `odig`, and how consistency helps with the build/package/release cycle — and also how we can use automated tooling for mass changes. It doesn't have to be long. Just enough to demonstrate that things are better :)

Having such a post would allow us to reference it from future announcements/posts/tweets.  

cc @GemmaG

**Comment by GemmaG** [comment]
Might be good to have separate posts for each of the following (with more detail) and another more general post linking them all together with the focus on workflow improvements tying them all together that we can post on mirage.io

- build/package:  topkg and odig
- release process: opam 2.0 additions
- documentation: odoc
- testing: CI improvements
- logging and error improvements

**Comment by avsm** [comment]
agreed with list: would move opam2 and testing down to the bottom and prioritise the developer facing ones: build, docs and logging in the very short term.

**Comment by amirmc** [comment]
This sounds great but I was hoping for a post that could be up and public sometime in the next two weeks. Is that the general one you’re referring to @GemmaG?  If so, that would be ideal.  I’m imagining an intro post that has short summaries and subsequent posts with details. That would mean I can still link to the first (general) one, without having to wait for the whole set.

Let me know if you were thinking of something different or if the above seems unfeasible.

**Comment by yomimono** [comment]
Closing this out as we're tracking blog posts elsewhere.
