### ISSUE TITLE
Fix/update scripts for build and deploy of the website

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#531]
There have been some changes to the artefacts produced via build steps, which mean various scripts need to be updated. 

Mindy said: 
>there's no `mir-` prefix and the `.`s are stripped from the output name so instead it should look for `src/mirageio.xen` and `src/openmirageorg.xen`

This will also involve changes to the scripts in https://github.com/mirage/mirage-www-deployment

**Comment by avsm** [comment]
fixed this locally on the deployment machine, and via https://github.com/ocaml/ocaml-ci-scripts/pull/156

will open a PR for mirage-www-deployment after testing a bit more

**Comment by yomimono** [comment]
@avsm, can you confirm that these are working?  It looked like there was a bit of downtime with the last merge, but I think it's fine as long as it didn't boot due to manual intervention.

**Comment by amirmc** [comment]
Another blog post is merged and building but the scripts in the deploy repo haven't been updated.  Are things up to date on the deployment machine itself or have they been manually booted so far? cc @avsm and @mor1

**Comment by avsm** [comment]
Things are uptodate on the deployment machine but not pushed to the repo -- sorting now.

**Comment by yomimono** [comment]
@avsm please push to the repo today if you have time.

**Comment by yomimono** [comment]
We discussed this tarpit in the biweekly call today and we'll have mirage-www use its own deploy scripts, outside of ocaml-ci-scripts.   That will also free up the `mirage` deploy script in `ocaml-ci-scripts` to be more useful in the general case (see https://github.com/ocaml/ocaml-ci-scripts/pull/162 ).

**Comment by yomimono** [comment]
It looks like http://solo5.mirage.io/ is not getting updates alongside https://mirage.io - @avsm, was this a TODO?

**Comment by mato** [comment]
Do we have the website deployment chain documented somewhere? I'd like to look into having DNS-load-balanced instances running on Solo5 but have no idea where to start.

**Comment by mor1** [comment]
Possibly not :(

It's a bit old school. I suspect this should be made better with Datakit at some point (?)

Last I looked, the `mirage-www-deployment` repo linked above has the scripts. The basic idea is: 
* when a PR to `mirage-www` is merged, 
  * the Travis CI script builds it and, 
  * if successful, commits the Xen build outputs to `mirage-www-deployments`; 
* meanwhile, there's a cronjob running on the deployment host
  * executing `git pull` on the deployment repo periodically and, 
  * when an update to that repo is merged (typically due to a new build artefact having been committed by Travis), running a post-merge script that kills the current site and boots the new one.

Does that help? Happy to answer questions on IRC/Slack if needed.

**Comment by amirmc** [comment]
@mato, the summary by @mor1 is my understanding of how things are meant to work.  There are some very out of date pseudo-docs in a blog post from a while ago, but I think a number of details have changed since then (http://amirchaudhry.com/heroku-for-unikernels-pt1#the-scripts-for-decksopenmirageorg)

**Comment by mato** [comment]
@amirmc @mor1 Thanks both of you, I'll look into setting something up for Solo5 when I have time.

**Comment by yomimono** [comment]
https://github.com/ocaml/ocaml-ci-scripts/pull/162 was just merged and will require changes to `mirage-www` for deployments and testing to work again.  I'm not available to make those changes until late July at the earliest.  Perhaps @mor1 , @avsm , @amirmc , @talex5 , or @samoht has time to fix the build?

**Comment by samoht** [comment]
As I have merged the offending PR, I will have fix the build :-)

**Comment by mor1** [comment]
Related to this-- does anyone think it would be a good idea / have strong objections to me putting together a PR to cause `mirage-www` to be built with [dommage](https://github.com/mor1/dommage)? (Ie., containerising the build environment)

**Comment by samoht** [comment]
@mor1 not al all. Anything which make the deployment of mirage-www faster and simpler is welcome. Do you want me to try to fix the build before and your are taking care of this as well?

**Comment by mor1** [comment]
Let me take a look now-- hopefully I can fix in passing.

**Comment by mor1** [comment]
Ok-- I've had a crack at this. Need to fix the `dommage-deploy` script, but seems to work for me otherwise (cf #561). Will be fixing up the deployment end.

**Comment by yomimono** [comment]
Thanks for your work on this, @mor1 :)

**Comment by avsm** [comment]
Using ocurrent for deployment since #677
