### ISSUE TITLE
Blog feed does not validate

### ISSUE THREAD

**Issue by crd477** [mirage/mirage-www#548]
I want to subscribe to the blog in Thunderbird but the feed does not seem to validate.  validator.w3.org implicates `Undefined root element: atom:tag`:

[http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmirage.io%2Fblog%2Fatom.xml](http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmirage.io%2Fblog%2Fatom.xml)

**Comment by crd477** [comment]
Has anyone had a chance to look at this?  I'd love to get notifications for new entries to your blog.

**Comment by yomimono** [comment]
Thanks for the report, @crd477 , and your patience on a reply .  @samoht @djs55 or @avsm , do you know how the RSS feed is generated (I suspect via Cowabloga)?

**Comment by djs55** [comment]
My guess is that `cowabloga` uses `cow`. This looks suspicious: https://github.com/mirage/ocaml-cow/blob/master/src/cow_atom.ml

**Comment by yomimono** [comment]
Ah, indeed; some attention there could probably resolve this issue as well as https://github.com/mirage/mirage-www/issues/319 .

**Comment by crd477** [comment]
I recently watched @yomimono's 34c3 talk (great job, BTW) and was reminded of this problem.
I just did some manual XML dorking and it looks like simply replacing `<tag ...>` and `</tag>` with `<feed ...>` and `</feed>` allows it to pass the W3 Feed Validation Service.

**Comment by hannesm** [comment]
good news, everyone: I analysed and debugged the same issue as @crd477 @djs55 and provided a pull request https://github.com/mirage/ocaml-cow/pull/101 (this won't solve #319)
once that is merged + released, and mirage-www is redeployed, there'll be a validating feed again :)

sorry that it took so long (and I only after debugging and opening the PR came across this issue)

**Comment by samoht** [comment]
https://github.com/ocaml/opam-repository/pull/11896 and https://github.com/ocaml/opam-repository/pull/11979 have been merged, and I have just re-trigered a TravisCI build for mirage-www so hopefully the feed should validate pretty soon now.

**Comment by samoht** [comment]
Re-opening as the feed is still broken ...

**Comment by samoht** [comment]
Right, it took a bit of time to shutdown the previous VM, so the new one now validates. Yay!
