### ISSUE TITLE
Expired certificate used for mirage.io

### ISSUE THREAD

**Issue by aluuu** [mirage/mirage-www#601]
Hello,

Problem:
I've just spotted that certificate which is deployed on mirage.io has expired a couple of hours ago. 

Steps to reproduce:
```
% echo | openssl s_client -showcerts -servername mirage.io -connect mirage.io:443 2>/dev/null | openssl x509 -inform pem -noout -text | grep -A2 Validity
        Validity
            Not Before: Nov  1 15:01:47 2017 GMT
            Not After : Jan 30 15:01:47 2018 GMT
```
or just open https://mirage.io in your browser.

Could you please fix this?

**Comment by yomimono** [comment]
belated thanks for the notification :) the current cert is good until may 1, 2018.

**Comment by aluuu** [comment]
Hooray, thanks!
