### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#606]
the let's encrypt certificate for mirage.io expired on may 1st... /cc @avsm

**Comment by avsm** [comment]
renewed (and udns deployment back on the todo list)

**Comment by hannesm** [comment]
3 months later, the certificate again expired...

**Comment by dromer** [comment]
It's called a 'cronjob' people :stuck_out_tongue:

**Comment by dmbaturin** [comment]
...and the web server plugins can even setup it by themselves. :)

**Comment by sidkshatriya** [comment]
@avsm The certificate has expired again. As suggested above, an auto-renew cronjob will help though that might be difficult if the website itself is a microkernel...

**Comment by sthibaul** [comment]
The certificate of mirage.io has expired again :)

**Comment by gavinbeatty** [comment]
Expired today, May 16.

**Comment by hannesm** [comment]
expired today again, on august 15th...

**Comment by mircea-cosbuc** [comment]
expired today, on November 14

**Comment by stensonb** [comment]
my turn!!  :)  now expired: Feb 12 2020 12:50 UTC

**Comment by knobo** [comment]
So... Should I say something? It is May...

**Comment by dmbaturin** [comment]
Are the maintainers secretly doing it to see if there are any visitors that care about the website? ;)

**Comment by hannesm** [comment]
thanks for your reminder. now, 2 years later we finally have a deployment for https://mirage.io where the let's encrypt issuance and renewal is automated using MirageOS unikernels and ocaml-letsencrypt :D it's definitively worth a blog post / tutorial how to get there.
