### ISSUE TITLE
Is the example in the Lwt tutorial correct?

### ISSUE THREAD

**Issue by naartjie** [mirage/mirage-www#642]
Should this [line](https://github.com/mirage/mirage-www/blame/ff9d904444d1d40ade447179552d071d99e95633/tmpl/wiki/tutorial-lwt.md#L306) in the tutorial:

```ocaml
  let t = OS.Time.sleep_ns (Duration.of_sec 1) -> raise (Failure "late failure") in
  ...
```

not read like this instead?

```ocaml
  let t = OS.Time.sleep_ns (Duration.of_sec 1) >>= fun () -> raise (Failure "late failure") in
```

**Comment by hannesm** [comment]
yes - you are right, would you mind filing a PR to this repository?

**Comment by naartjie** [comment]
Thanks @hannesm, PR #643
