### ISSUE TITLE
Setup through dockerfile

### ISSUE THREAD

**Issue by Alakazam03** [mirage/mirage-www#666]
I am trying running mirage-www as a container. I built the image using dockerfile
`docker build -t mirage-www .` and then ran it using `docker run -it mirage-www`.

Output: 2020-02-24 12:01:56 +00:00: INF [tcpip-stack-socket] Manager: connect
2020-02-24 12:01:56 +00:00: INF [tcpip-stack-socket] Manager: configuring
2020-02-24 12:01:58 +00:00: INF [dispatch] Listening on http://localhost/

I am not able to access or identify the port. I am new to ocaml as well as mirageos. Sorry for newbie question. @olleolleolle @btbytes @jerith

**Comment by talex5** [comment]
You'll need to tell Docker to connect a port on the host to the container, e.g.

```
docker run -it -p 8080:80 mirage-www
```

Then visit <http://localhost:8080/>

**Comment by Alakazam03** [comment]
Hi thanks for the reply. I am trying to a unikernel inside a container for a college project. I pulled unikernel/mirage image from docker hub and tried running skeleton applications from github. But i am getting some errors in achieving that. Please can someone explain me the concept and how to go forward? @talex5 @olleolleolle
