### ISSUE TITLE
docs.mirage.io gives a 404 error

### ISSUE THREAD

**Issue by slegrand45** [mirage/mirage-www#681]
Hello,

If i click on the API tab from https://mirage.io/, i get a 404 error.

The tab is defined here: https://github.com/mirage/mirage-www/blob/88b5e763ea8e9685c437bfb298171f1afbafab91/src/pages.ml#L59

**Comment by talex5** [comment]
Looks like this is the cause: https://github.com/mirage/docs/issues/4

**Comment by hannesm** [comment]
thanks for your report, it is working now again (thanks to @dinosaure)
