### ISSUE TITLE
remove generated stuff from repo

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#720]
in #719 @TheLortex mentions that `data/mirageio_data.ml` is auto-generated (has a dune rule) and should not be part of this repository (/cc @tmattio)

**Comment by tmattio** [comment]
IIRC, we did it this way in ocaml.org because we wanted the data to be used elsewhere (a ReScript code base).
There's no reason to have the data exposed as a library for Mirage's website as far as I can tell, so it should be good to remove the generated modules from the codebase.
