### ISSUE TITLE
Build error while running `make build`

### ISSUE THREAD

**Issue by davisuga** [mirage/mirage-www#757]
OS: Linux Mint 20.02 Uma
OCaml: 4.14
Opam: 2.1.0
Dune: 3.0.3

Output: 

```bash
opam exec -- dune build --root .
File "mirage/duniverse/ocaml-graphql-server/dune-project", line 2, characters 14-17:
2 | (using menhir 2.0)
                  ^^^
Warning: Version 2.0 of the menhir extension is not supported until version
1.4 of the dune language.
Supported versions of this extension in version 1.1 of the dune language:
- 1.0
File "mirage/dune.build", line 14, characters 42-50:
14 |    mirage-runtime mirage-time mirage-unix mirageio tcpip.stack-socket
                                               ^^^^^^^^
Error: Library "mirageio" not found.
-> required by _build/default/mirage/main.exe
-> required by alias mirage/all
-> required by alias default
File "mirage/duniverse/dream/src/vendor/paf/lib/paf.ml", line 345, characters 16-17:
345 |         | Error e ->  Logs.info (fun m -> m "Error: unknown"); Lwt.return ()));
                      ^
Error (warning 27 [unused-var-strict]): unused variable e.
make: *** [Makefile.user:22: build] Error 1
```

**Comment by d-s-d** [comment]
I have the same issue on OS x.

`➜  mirage-www git:(master) ✗ uname -a
Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64`

`
opam exec -- dune build --root . @install
-e \e[2musing overlay repository mirage: [opam-overlays, mirage-overlays] \e[0m
[opam-overlays] no changes from git+https://github.com/dune-universe/opam-overlays.git
[NOTE] Repository opam-overlays has been added to the selections of switch /.../mirage-www only.
       Run `opam repository add opam-overlays --all-switches|--set-default' to use it in all existing switches, or in newly created switches, respectively.

[mirage-overlays] no changes from git+https://github.com/dune-universe/mirage-opam-overlays.git
[NOTE] Repository mirage-overlays has been added to the selections of switch /.../mirage-www only.
       Run `opam repository add mirage-overlays --all-switches|--set-default' to use it in all existing switches, or in newly created switches, respectively.

 ↳ generate lockfile for monorepo dependencies
==> Using 1 locally scanned package as the target.
==> Found 145 opam dependencies for the target package.
==> Querying opam database for their metadata and Dune compatibility.
==> Calculating exact pins for each of them.
==> Wrote lockfile with 99 entries to mirage/mirage/www-macosx.opam.locked. You can now run opam monorepo pull to fetch their sources.
-e \e[2mremoving overlay repository [opam-overlays, mirage-overlays]\e[0m
Repositories removed from the selections of switch /.../mirage-www. Use '--all' to forget about them altogether.
Repositories removed from the selections of switch /.../mirage-www. Use '--all' to forget about them altogether.
 ↳ opam install switch dependencies
Nothing to do.
 ↳ install external dependencies for monorepo
==> Using lockfile mirage/mirage/www-macosx.opam.locked
 ↳ fetch monorepo rependencies in the duniverse folder
==> Using lockfile mirage/mirage/www-macosx.opam.locked
Successfully pulled 99/99 repositories
opam exec -- dune build --root .
File "mirage/duniverse/dream/src/vendor/paf/lib/paf.ml", line 345, characters 16-17:
345 |         | Error e ->  Logs.info (fun m -> m "Error: unknown"); Lwt.return ()));
                      ^
Error (warning 27 [unused-var-strict]): unused variable e.
make[1]: *** [build] Error 1
make: *** [all] Error 2

`

**Comment by TheLortex** [comment]
Hi, thanks for reporting the issue. 
To help investigating its cause, can you check if there is a `dune` file in the `mirage/duniverse/` folder ? If so, what is its content ?

**Comment by d-s-d** [comment]
@TheLortex thanks for the quick response!

here again the command that I'm running ...

```
$ dune build mirage/
File "mirage/duniverse/dream/src/vendor/paf/lib/paf.ml", line 345, characters 16-17:
345 |         | Error e ->  Logs.info (fun m -> m "Error: unknown"); Lwt.return ()));
                      ^
Error (warning 27 [unused-var-strict]): unused variable e.
File "dune", line 13, characters 9-20:
13 |     (run tailwindcss build -c tailwind.config.js -i template/styles.css -o
              ^^^^^^^^^^^
Error: Program tailwindcss not found in the tree or in PATH
 (context: default)
```

and the content of the `dune` file ...


```
$ cat mirage/duniverse/dune
; This file is generated by opam-monorepo.
; Be aware that it is likely to be overwritten by your next opam monorepo pull invocation.

(vendored_dirs *)
```

**Comment by TheLortex** [comment]
For the tailwind error, please install tailwind either using the instructions found on https://tailwindcss.com/docs/installation or via opam: `opam pin git+https://github.com/tmattio/opam-tailwindcss#fb0f82edd09999f7be033ab1785ba5f6b60ed8f6`

The other one is trickier: the `(vendored_dirs *)` is supposed to make dune ignore warnings in the `duniverse` subtree.

I'll try to reproduce in a fresh installation. Are you using OCaml 4.14 too ?

**Comment by TheLortex** [comment]
Using `dune build --profile release mirage/` should go through. 

However it remains unexpected that a warning from a package in the `duniverse/` folder is being treated as an error. I'll open an issue on that matter.

**Comment by d-s-d** [comment]
the exact steps that I take

```
$ opam switch
#   switch   compiler      description
->  default  ocaml.4.14.0  default

$ make switch
opam switch create . --no-install -y

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml" {>= "4.05.0"}]

/* etc. etc. */

opam install --deps-only --with-test --with-doc -y .
The following additional pinnings are required by mirageio.~dev:
  - dream.dev at git+https://github.com/TheLortex/dream.git#650b216d0f8b6f322110b80f03eaa5183b88a8d4
  - dream-mirage.dev at git+https://github.com/TheLortex/dream.git#650b216d0f8b6f322110b80f03eaa5183b88a8d4
  - dream-pure.dev at git+https://github.com/TheLortex/dream.git#650b216d0f8b6f322110b80f03eaa5183b88a8d4
  - dream-httpaf.dev at git+https://github.com/TheLortex/dream.git#650b216d0f8b6f322110b80f03eaa5183b88a8d4
  - tailwindcss.dev at git+https://github.com/tmattio/opam-tailwindcss#fb0f82edd09999f7be033ab1785ba5f6b60ed8f6
Pin and install them? [Y/n] y

/* etc. etc. */

<><> mirage-stack.4.0.0 installed successfully ><><><><><><><><><><><><><><><><>
=> This package is deprecated. Please use the module types in Tcpip.Stack directly.

$ make deps

/* etc. */

$ make build
opam exec -- dune build --root .
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

Done in 228ms.
File "mirage/duniverse/dream/src/vendor/paf/lib/paf.ml", line 345, characters 16-17:
345 |         | Error e ->  Logs.info (fun m -> m "Error: unknown"); Lwt.return ()));
                      ^
Error (warning 27 [unused-var-strict]): unused variable e.

/* etc. etc. */

configuration successful!
now type "make" to build
then type "make install" or "sudo make install" to install
make: *** [build] Error 1

$ dune build --profile release mirage/
$ # this indeed seems to work :-) 
```

**Comment by samoht** [comment]
I believe those installation errors are now fixed. Please re-open if not!
