### ISSUE TITLE
unikernel fails to build for non-unix targets

### ISSUE THREAD

**Issue by RyanGibb** [mirage/mirage-www#766]
```
File "duniverse/Zarith/dune", line 22, characters 12-16:
22 |  (libraries unix)
                 ^^^^
Error: Library "unix" in
/home/ryan/.opam/default/solo5-sysroot/lib/ocaml
is hidden (unsatisfied 'exist_if').
-> required by _build/solo5/duniverse/Zarith/discover.exe
-> required by _build/solo5/duniverse/Zarith/gmp.env
-> required by _build/solo5/duniverse/Zarith/Makefile
-> required by _build/solo5/duniverse/Zarith/libs.sexp
-> required by _build/solo5/duniverse/Zarith/zarith.cmxa
-> required by _build/solo5/mirage/main.exe
-> required by _build/solo5/mirage/www.hvt
-> required by _build/solo5/mirage/dist/www.hvt
-> required by alias mirage/dist/all (context solo5)
-> required by alias mirage/dist/default (context solo5)
```

This is caused by Zarith=1.12+dune depending on unix:
https://github.com/dune-universe/Zarith/blob/512da67bd11f41f7c51c846e971de7bcac3ab9b7/dune#L22

**Comment by dinosaure** [comment]
You shouldn't take the `Zarith+dune` version but the `Zarith+dune+mirage1` version. What is your workflow? Did you invoke `opam monorepo` with `--require-cross-compile`?

**Comment by RyanGibb** [comment]
Yes I've just realized this! (Pretty much exactly at your comment.)  I'm using nix to build mirage-www with this project: https://github.com/RyanGibb/hillingar. The problem was I wasn't using https://github.com/dune-universe/mirage-opam-overlays/. This commit fixes the issue https://github.com/RyanGibb/opam-nix/commit/a110a9a4e146c95975a4aa9c2a7809333da4cba8
