### ISSUE TITLE
curl -sI https://mirage.io returns 404 but works fine without -I

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/mirage-www#774]
```
$ curl -sI https://mirage.io
HTTP/1.1 404 Not Found
Content-Length: 0

```
It's not bad bug or anything but this might be a display of a problem in one of the libraries

**Comment by TheLortex** [comment]
Dream has nothing to handle `HEAD` requests, so by default its `404`.
In ocaml.org they also had this issue, here's the patch: https://github.com/ocaml/ocaml.org/pull/576/files
