### ISSUE TITLE
new website: atom / rss feed?

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#782]
Hi,

I couldn't find any advertisement of the feed.xml on the new website (I had to look into the code to figure out that there is still an atom feed)... Shouldn't there be a `<link rel="alternate" href="/feed.xml" title="MirageOS" type="application/atom+xml"/>` in the `<head>` of the main landing page?

Since I don't know much about web, it would be great if someone would chime in.

**Comment by TheLortex** [comment]
It's advertised on the blog section of the website, but it makes sense to advertise it on every page.
