### ISSUE TITLE
`Error: No rule found for asset/main.css`

### ISSUE THREAD

**Issue by RyanGibb** [mirage/mirage-www#796]
When building the project I'm getting the error `Error: No rule found for asset/main.css` because the dependancy https://github.com/mirage/mirage-www/blob/5dc832a346948377eb7f8f0947a4e415d8f4ce17/lib/dune#L11 which I think is broken because of https://github.com/mirage/mirage-www/commit/eafef49b64315194aa6ac6940ebf6c2e0079f5c1.

Should `../asset/main.css` be removed here?

**Comment by TheLortex** [comment]
`asset/main.css` is generated by the following rule, declared in https://github.com/mirage/mirage-www/blob/master/dune

```
(subdir
 asset/
 (rule
  (target main.css)
  (deps
   %{workspace_root}/tailwind.config.js
   %{workspace_root}/template/styles.css
   (glob_files %{workspace_root}/template/*.eml))
  (action
   (chdir
    %{workspace_root}
    (run tailwindcss build -c tailwind.config.js -i template/styles.css -o
      %{target})))))
```

So the error is a bit surprising.

**Comment by RyanGibb** [comment]
Interesting. It looks like the tailwindcss command was silently failing then. It looks like building it from source has fixed this https://github.com/mirage/mirage-www/pull/797/commits/434508c6eaa172dfd3603471b6e32bc095fc4421.
