### ISSUE TITLE
Install instructions partially outdated

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-www#801]
The installation instructions have been updated to Mirage 4, but the OS-specific instructions are not up to date. I believe we need a newer version of Ubuntu than 16.04 to get opam>=2.1, and for Debian stable (which is now Bullseye, not Buster) the version of opam in the repository is 2.0.8. I suspect the FreeBSD instructions are outdated as well.

https://github.com/mirage/mirage-www/blob/master/data/wiki/install.md#ubuntu-1604-xenial-or-higher

**Comment by samoht** [comment]
Do you mind opening a PR to fix those? Many thanks!
