### ISSUE TITLE
deploy.ocamllabs.io

### ISSUE THREAD

**Issue by mtelvers** [mirage/mirage-www#803]
We would like to decommission the [ocamllabs.io]() domain.

Please can we move the Mirage website deployer, currently running at https://deploy.ocamllabs.io, to [deploy.mirage.io]()?

Tasks:
- [x] Create `deploy.mirage.io` as a new A record pointing to `51.159.31.165`
- [x] Update the GitHub application providing webhooks in github.com/mirage to use the new URL

cc @samoht

**Comment by hannesm** [comment]
Dear @mtelvers, thanks for your report. The A record for deploy.mirage.io is live. A HMAC key (for let's encrypt provisioning is also available, reach out via encrypted email (or take a look into the private mirageos-zone git repository)).

**Comment by mtelvers** [comment]
@hannesm Thank you for adding the DNS entry.  I do not have access to the `mirageos-zone` repository.  I have sent you a digitally signed email, so we can establish encrypted communication.

**Comment by mtelvers** [comment]
@hannesm Thank you again.  I have completed the updates.

The Let's Encrypt certificates are deployed via RFC2136.

**Comment by hannesm** [comment]
Ah, ignore my previous comment -- https://github.com/ocurrent/ocurrent-deployer/pull/174 seems to be what was needed.
