### ISSUE TITLE
Hello world tutorial step 2 outdated

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-www#806]
The step 2 of the hello world tutorial (device-usage/block) is not up to date with mirage-skeleton. Specifically, it uses `~deps` instead of `~extra_deps`.

**Comment by hannesm** [comment]
Could you please provide a pull request with the change? thanks a lot!

**Comment by reynir** [comment]
I will submit a pull request after I have addressed https://github.com/mirage/mirage-skeleton/issues/358

**Comment by reynir** [comment]
I believe this was addressed in one or more PRs this summer.
