### ISSUE TITLE
Blog link is broken on site

### ISSUE THREAD

**Issue by Zachiah** [mirage/mirage-www#811]
I have basically no context on this project and I apologize if this is the wrong repo but the blog link on the main page is causing a 500 error:

https://github.com/mirage/mirage-www/assets/50641830/ba378dab-b8e4-4ea4-b91a-4b77b539c89c

**Comment by reynir** [comment]
The link in question is https://mirage.io/blog. I tried to build and reproduce locally but failed, but I can confirm your observation in "production".
