### ISSUE TITLE
hyperlinks are broken (again?)

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-www#816]
Dear Madam or Sir,

I just noticed at https://mirage.io/blog/introducing-ocaml-tls that the links at the bottom pointing to the blog series posts are all redirecting to the frontpage of mirage.io

I still wonder, when there was the very nice relayout and rework of the internals, did anyone bother to check hyperlinks? Is there someone interested in (more automatically) testing and fixing these internal hyperlinks?

Thanks for reading!

**Comment by samoht** [comment]
While the footer notes seem broken, the bottom links seem to be working now (unless I am not looking at the right place). Could you check this is still broken for you?

**Comment by hannesm** [comment]
At least for me, if I go to https://mirage.io/blog/introducing-ocaml-tls and browse to the end, to click on the hyperlink labeled "[OCaml-TLS: building the nocrypto library core](http://mirage.io/blog/introducing-nocrypto)", I end up on the frontpage.

**Comment by hannesm** [comment]
There's a potpourri of links to "https://mirage.io" and "http://mirage.io" -- while nearly all links on mirage.io itself should not name the hostname, i.e. link to "/blog/foo/bar"!? I suspect that means some busy work, in addition I'd appreciate to check whether the link target exists (plus a way/pre-commit hook that future changes won't introduce links-with-mirage-io-as-hostname, neither broken links)... but I do think it is necessary to do since the generations of reworks on mirage-www broke just a little bit too much...

**Comment by samoht** [comment]
> At least for me, if I go to https://mirage.io/blog/introducing-ocaml-tls and browse to the end, to click on the hyperlink labeled "[OCaml-TLS: building the nocrypto library core](http://mirage.io/blog/introducing-nocrypto)", I end up on the frontpage.

That's very odd, when I click on that link that redirects me to https://mirage.io/blog/introducing-nocrypto !

**Comment by hannesm** [comment]
same issue as #790 -- and also:

```
$ curl -v 'http://mirage.io/blog/introducing-nocrypto'
* Host mirage.io:80 was resolved.
* IPv6: (none)
* IPv4: 147.75.34.212
*   Trying 147.75.34.212:80...
* Connected to mirage.io (147.75.34.212) port 80
> GET /blog/introducing-nocrypto HTTP/1.1
> Host: mirage.io
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://mirage.io
< Content-Length: 0
< 
* Connection #0 to host mirage.io left intact
```

while the location should have been https://mirage.io/blog/introducing-nocrypto
